### ISSUE TITLE
Is this possible to change the appear location?

### ISSUE THREAD

**Issue by tedwong** [xtrinch/react-touch-screen-keyboard#19]
As title, thanks.

**Comment by xtrinch** [comment]
You could easily style .keyboard-wrapper as desired to put it into the location you require.

**Comment by reganlawton** [comment]
@tedwong I personal override the CSS and @xtrinch said above its the simplest method.

**Comment by xtrinch** [comment]
Also, you can now add your own class via prop keyboardClassName.
