### ISSUE TITLE
creating input event does not work in IE

### ISSUE THREAD

**Issue by neo6238** [xtrinch/react-touch-screen-keyboard#2]
IE raises an error when creating an Event like in 

_inputNode.dispatchEvent(new Event('input'));_

It just is not supported and there were a polyfill...

http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work

Maybe you'll want to handle within the module?  I just wanted to let you know...

**Comment by xtrinch** [comment]
Yes this library was mainly tested with chrome, I am however accepting pull requests :)

**Comment by reganlawton** [comment]
Possibly a quick fix using https://github.com/krambuhl/custom-event-polyfill and changing to `inputNode.dispatchEvent(new CustomEvent('input'));`

Throughts?

**Comment by xtrinch** [comment]
Looks like a viable option

**Comment by reganlawton** [comment]
@xtrinch I'm installing it and test to check `CustomEvent` still works. Everywhere says it should.

If it works I'll push a PR for it

**Comment by reganlawton** [comment]
Resolved using `custom-event-polyfill` package.
