### ISSUE TITLE
How to change keyboard size?

### ISSUE THREAD

**Issue by shrupa** [xtrinch/react-touch-screen-keyboard#22]
The 'class' property exposed affects only the input field. How can I increase the keyboard size?

**Comment by xtrinch** [comment]
I suppose a keyboardClassName could be added to parameters and passed along to the keyboard. Will update the package with this option, along with changing className to inputClassName, so we know which is which.

**Comment by shrupa** [comment]
Thank you for your response. Do you have a rough timeline in mind?
Thanks again!

**Comment by xtrinch** [comment]
Well you have to use the child classes also, and increase the buttons.
