### ISSUE TITLE
Enter key (green button) is displaying wingdings "â†§" instead of the normal icon shown in examples

### ISSUE THREAD

**Issue by smmschaefer** [xtrinch/react-touch-screen-keyboard#27]
I have the keyboard working just fine, but I have one problem.  The enter key (green button), is displaying "â†§" instead of what is shown in the examples.  I have been looking everywhere in the code for where I could change this, but haven't been able to find anything.

Any suggestions?

**Comment by xtrinch** [comment]
You could add a custom keyboard.

Also, if you open the key in the developers console, which character is there?

I would like more info, as I cannot reproduce the issue.

**Comment by smmschaefer** [comment]
Sorry about the delay, I have been out of town.  No key comes up in dev console when enter is pressed.  I'll see if I can get a custom keyboard working - I was hoping that I could just change the displayed value of the enter button only.

**Comment by smmschaefer** [comment]
The custom mapping doesn't let me change the shift button.  I can change the mappings for Q-.com, but I can't change the shift key's text.  No character comes up in the dev console, but the enter button works fine.  For whatever reason the green shift button is stuck saying "â†§".  I'm guessing that the symbol is being lost in translation somewhere.

**Comment by reganlawton** [comment]
What keyboard mapping do you have @smmschaefer ?

**Comment by smmschaefer** [comment]
I'm using the US style keyboard.  I attached a screen shot of what the keyboard looks like when it probs.  Notice the enter key has "â†§"

![keysnip](https://user-images.githubusercontent.com/19543988/36806304-7d18f158-1c74-11e8-9b96-228fa5dbed56.PNG)

**Comment by reganlawton** [comment]
@smmschaefer I was asking about your  computers language settings sorry.

**Comment by smmschaefer** [comment]
It's EN (United States) - US

**Comment by smmschaefer** [comment]
@xtrinch 

Here is another screen shot of it.  This bug seems to happen on different operating systems.  I built the program on a different computer (Mac OS - other one was from Windows).  Could it be something with the chosen font for the website?

<img width="690" alt="macss" src="https://user-images.githubusercontent.com/19543988/37108883-59c277dc-21ed-11e8-9dc7-80b8a56f228c.png">

**Comment by xtrinch** [comment]
It could have. Worth a try using the html unicode &something; format instead of the character actually residing in code. @reganlawton care to try?

**Comment by reganlawton** [comment]
Yeah I'll give it a refactor and push a branch and tag it here.

**Comment by smmschaefer** [comment]
sweet

**Comment by reganlawton** [comment]
@smmschaefer  give https://github.com/xtrinch/react-touch-screen-keyboard/pull/31 a try

**Comment by reganlawton** [comment]
May need a rebuild locally

**Comment by reganlawton** [comment]
See new release @ 0.3.4

**Comment by smmschaefer** [comment]
I'll try it today
