### ISSUE TITLE
Can't set container div's className

### ISSUE THREAD

**Issue by MarkEhr** [xtrinch/react-touch-screen-keyboard#35]
I have an inline input. For this to work I would need to set the display property of the outbounding div to `display: inline-block`.
If I could set a class to this div through props I wouldn't have to wrap it up in another element to apply css to this div or make another `Input` component just to apply this class.

**Comment by reganlawton** [comment]
@MarkEhr submit a PR with an update to the examples and I'll review and merge if ok.

**Comment by reganlawton** [comment]
Merged to master
