### ISSUE TITLE
new feature : can use keyboardInput with inputgroup

### ISSUE THREAD

**Issue by jphautin** [xtrinch/react-touch-screen-keyboard#46]
I do not find a solution to use _keyboardInput_  inside a _input-group_ because the component is inserting a div up to the real input.
If we make the input at the same level of the keyboard container, this could perhaps work ?

**Comment by reganarkade** [comment]
@jphautin Could you provide some mock HTMl markup to demo your concept for more visual clarity? 

As if might aim with another feature we are trying to tackle.

**Comment by reganlawton** [comment]
@jphautin Could you provide some mock HTMl markup to demo your concept for more visual clarity?

As if might aim with another feature we are trying to tackle.

**Comment by jphautin** [comment]
Ok. I do not get it.

let explain a bit. I am using reactstrap to use react+bootstrap.


Here the code I use normally for a input group:

>                 <div>
>                    <InputGroup>
>                        <Input
>                            placeholder="search"
>                            name="search"
>                            type="text"
>                           value={this.props.text}>
>                        </Input>
>                        <InputGroupAddon addonType="append">
>                            <Button color="secondary">search</Button>
>                        </InputGroupAddon>
>                    </InputGroup>
>                </div>


So, for the KeyboardedInput, I would expect the same code was going to give me the same:

 >               <div>
 >                   <InputGroup>
 >                       <KeyboardInput placeholder="search"
 >                                      name="search"
 >                                      type="text"
 >                                      value={this.props.text}>
 >                       </KeyboardInput>
 >                       <InputGroupAddon addonType="append">
 >                           <Button color="secondary">search</Button>
 >                       </InputGroupAddon>
 >                   </InputGroup>
 >               </div>

I also try what I understood from Luke suggestion:


>                <div>
>                    <InputGroup>
>                        <KeyboardInput containerClassName={"input-group"}
>                                       placeholder="search"
>                                       name="search"
>                                       type="text"
>                                       value={this.props.text}>
>                        </KeyboardInput>
>                        <InputGroupAddon addonType="append">
>                            <Button color="secondary">search</Button>
>                        </InputGroupAddon>
>                    </InputGroup>
>                </div>

But in both case the result are not exactly the same:
