### ISSUE TITLE
Feature: if keyboard has isDraggable=false remove shadow

### ISSUE THREAD

**Issue by LukaszGrela** [xtrinch/react-touch-screen-keyboard#47]
Shadow makes sense on dragable keyboard, it raises it above the surface, but non-dragable should not have it. Also `react-dragable` css class is added even when it is not dragable could this be removed too?

**Comment by LukaszGrela** [comment]
Also useful would be to allow to assign custom class name to `Keyboard` component :) thanks

**Comment by reganlawton** [comment]
@LukaszGrela Sorry for the late reply here. It should be easy enough to remove using styling. As the keyboard initial had shadow styling before @xtrinch added the draggable feature and I've checked and confirm this is still the case.
