### ISSUE TITLE
Keyboard icon show bigger than the container

### ISSUE THREAD

**Issue by enricoirawan** [xtrinch/react-touch-screen-keyboard#58]
![Screenshot (1)](https://user-images.githubusercontent.com/54756728/169971826-669975ca-0783-4dcc-a88b-0849d0cf44b2.png)

Hello, thank you for your effort to make this awesome lib
i want to ask why in my project the icon of the keyboardedinput show bigger like this????

**Comment by reganlawton** [comment]
@enricoirawan you might want to check the CSS around those and revert them. As I believe your CSS reset might be causing the issue.

This is without knowing more information.

**Comment by enricoirawan** [comment]
how i can search the icon size did you use?

**Comment by reganlawton** [comment]
@enricoirawan I can't see the comment that you added in Github but you can use the dev console in the browser to see the overrides

**Comment by enricoirawan** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/54756728/170185806-aab5af78-fdb7-4510-8f89-da26b6602c6f.png)

Its solved now, thx

**Comment by reganlawton** [comment]
Glad to hear it 👍
